
----------------------------- SCHEMA.SQL ----------------------------- 


CREATE TABLE PATIENTS(
  ID INT GENERATED ALWAYS AS IDENTITY,
  NAME TEXT,
  DATE_OF_BIRTH DATE
);

CREATE TABLE MEDICAL_HISTORIES(
  ID INT GENERATED ALWAYS AS IDENTITY,
  ADMITTED_AT DATE,
  PATIENT_ID INT,
  STATUS TEXT,
  CONSTRAINT PATIENT_MEDICAL_HISTORY FORIEGN KEY(PATIENT_ID) REFERENCES PATIENTS(ID)
);

CREATE TABLE TREATMENTS(
  ID INT GENERATED ALWAYS AS IDENTITY,
  TYPE TEXT,
  NAME TEXT
);

CREATE TABLE INTERSECTION(
  MEDICAL_HISTORIES_ID INT,
  TREATMENTS_ID INT
  CONSTRAINT MEDICAL_HISTORIES_ID FORIEGN KEY(MEDICAL_HISTORIES_ID) REFERENCES MEDICAL_HISTORIES(ID),
  CONSTRAINT TREATMENTS_ID FORIEGN KEY(TREATMENTS_ID) REFERENCES TREATMENTS(ID)
);