
----------------------------- SCHEMA.SQL ----------------------------- 


CREATE TABLE PATIENTS(
  ID INT GENERATED ALWAYS AS IDENTITY,
  NAME TEXT,
  DATE_OF_BIRTH DATE
);

CREATE TABLE MEDICAL_HISTORIES(
  ID INT GENERATED ALWAYS AS IDENTITY,
  ADMITTED_AT DATE,
  PATIENT_ID INT,
  STATUS TEXT,
  CONSTRAINT PATIENT_MEDICAL_HISTORY FORIEGN KEY(PATIENT_ID) REFERENCES PATIENTS(ID)
);

CREATE TABLE TREATMENTS(
  ID INT GENERATED ALWAYS AS IDENTITY,
  TYPE TEXT,
  NAME TEXT
);

CREATE TABLE INTERSECTION(
  MEDICAL_HISTORIES_ID INT,
  TREATMENTS_ID INT
  CONSTRAINT MEDICAL_HISTORIES_ID FORIEGN KEY(MEDICAL_HISTORIES_ID) REFERENCES MEDICAL_HISTORIES(ID),
  CONSTRAINT TREATMENTS_ID FORIEGN KEY(TREATMENTS_ID) REFERENCES TREATMENTS(ID)
);

CREATE TABLE INVOICES(
  ID INT GENERATED ALWAYS AS IDENTITY,
  TOTAL_AMOUNT DECIMAL,
  GENERATED_AT TIMESTAMP,
  PAYED_AT TIMESTAMP,
  MEDICAL_HISTORY_ID INT,
  CONSTRAINT INVOICE_ID FOREIGN KEY(ID) REFERENCES INVOICE_ITEMS(INVOICE_ID)
);

CREATE TABLE INVOICE_ITEMS(
  ID INT GENERATED ALWAYS AS IDENTITY,
  UNIT_PRICE DECIMAL,
  QUANTITY INT,
  TOTAL_PRICE DECIMAL,
  INVOICE_ID INT,
  TREATMENT_ID INT,
  CONSTRAINT HISTORY_ID FOREIGN KEY(MEDICAL_HISTORY_ID) REFERENCES MEDICAL_HISTORIES(ID),
  CONSTRAINT TREATMENTS_ID FOREIGN KEY(TREATMENT_ID) REFERENCES TREATMENTS(ID)
);


